language: java 

sudo: false

os: osx
osx_image: xcode9.1
before_install:
  - bash .travis-prepare.sh

install: true

script:
  - xcodebuild -scheme JTouchBar-Debug
  - mvn -B clean install -f pom-debug.xml
  - xcodebuild -scheme JTouchBar-Release
  - mvn -B clean install -f pom.xml

cache:
  directories:
    - $HOME/.m2
    - $HOME/.binaries
